/*
 * Medical Records API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type MedicalAct struct {
	Id int `json:"id,omitempty"`

	UserId int `json:"user_id,omitempty"`

	HospitalId int `json:"hospital_id,omitempty"`

	MutuelleId int `json:"mutuelle_id,omitempty"`

	Metadata1 string `json:"metadata_1,omitempty"`

	Metadata2 string `json:"metadata_2,omitempty"`

	MontantTotal float32 `json:"montant_total,omitempty"`

	PriseEnChargeHopital float32 `json:"prise_en_charge_hopital,omitempty"`

	PriseEnChargeMutuelle float32 `json:"prise_en_charge_mutuelle,omitempty"`

	PriseEnChargePatient float32 `json:"prise_en_charge_patient,omitempty"`

	ConfirmationPaiementPatient bool `json:"confirmation_paiement_patient,omitempty"`

	ConfirmationMutuelle bool `json:"confirmation_mutuelle,omitempty"`

	ConfirmationRdv bool `json:"confirmation_rdv,omitempty"`

	PourcentagePriseEnCharge int `json:"pourcentage_prise_en_charge,omitempty"`

	Commentaire string `json:"commentaire,omitempty"`

	DateCreation time.Time `json:"date_creation,omitempty"`

	DatePrevue time.Time `json:"date_prevue,omitempty"`

	DateVenue time.Time `json:"date_venue,omitempty"`
}
