/*
 * Medical Records API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type User struct {
	Id int `json:"id,omitempty"`

	FirstName string `json:"first_name,omitempty"`

	Name string `json:"name,omitempty"`

	Password string `json:"password,omitempty"`

	IdGraulande string `json:"id_graulande,omitempty"`

	MutuelleId int `json:"mutuelle_id,omitempty"`
}
